In [53]:
import re
import pandas as pd

In [54]:
# f = open('WhatsApp Chat with Shauryaaa.txt', 'r', encoding='utf-8')
f = open('WhatsApp Chat with 2nd year CS -C unofficial group .txt', 'r', encoding='utf-8')

In [55]:
data = f.read()

In [56]:
print(data)

28/08/25, 07:58 - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
27/08/25, 18:30 - ~ Sumit created group "2nd year CS -C unofficial group "
28/08/25, 07:58 - You joined using this group's invite link
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:00 - +91 72360 60220: This message was deleted
28/08/25, 10:01 - +91 72360 60220:
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:01 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:02 - +91 72360 60220: <Media omitted>
28/08/25, 10:03 - +91 92354 97234 joined using a group link.
28/08/25, 10:53 - +91 95570 26316: Please come to E 105 for AEP lecture
28/08/25, 11:17 - Sarthak gcet joined using a group link.
28/08/25, 11:41 - ~ Shivi added ~ Siddhant
28/08/25, 11:48 - ~ Siddhant added ~ Sumit Kumar
28/08/25, 15:28 - ~ Sumit added Rudra Tyagi gcet, Vaibhav and ~ Vijay Thakur
28/08/25, 16:45 - +91 63861 82219 joined using a group link.
29/08/25, 14:46 - +91 88689 20172 joined using a group link.
29/08/25, 22:55 - Utkarsh joined using a group link.
30/08/25, 12:55 - ~ UDAY added ~ Riya Singh and ~ Utkarsh
31/08/25, 14:26 - +91 93103 03911: Kindly make groups of 6 for UHVPE activities and submit us the names by today
31/08/25, 16:04 - ~ Ridhima added Samprada gcet, Tarun gcet, ~ rhea and ~ rohit
31/08/25, 19:34 - +91 95570 26316: Send your group of 6 for UHVPE activities otherwise I will make a group
31/08/25, 21:25 - +91 95570 26316: Send me your group by 10 o’clock, otherwise I’ll put you in a random group.
31/08/25, 22:23 - +91 95570 26316: Group 1
Riya maurya
Shaurya sinha
Sneha yadav
Sanchali yadav
Samprada singh
Swayamparabha
31/08/25, 22:24 - +91 95570 26316: Group 2
Rishabh Mishra
Shivank yadav
Rahul
Rohan
Ritik
Sagar
31/08/25, 22:26 - +91 95570 26316: Group 3
Yash gautam
Utkarsh pathak
Rishu Ranjan
Vaibhav Kumar Dubey
Sachin Gupta
Tarush Tiwari
31/08/25, 22:26 - +91 95570 26316: Group 4
Sumit Kumar
Uday rana
Ujjwal pratap rana
Siddharth
Ridhima
Shreya
31/08/25, 22:37 - +91 95570 26316: Group 5
Rohit Kumar Singh
Raj Gupta
Rajveer Singh
Rishabh chauhan
Saurav Kumar
Satvik Srivastava
31/08/25, 22:32 - ~ Somyansh Rana added ~ 💀
31/08/25, 22:33 - ~ Somyansh Rana added ~ Shivanu Yadav
31/08/25, 22:40 - +91 95570 26316: Group 6
Rohit Kumar
Sumit Kumar
Sunny kumar
Shreya maurya
Sandhya Singh
Rishank deshwal
31/08/25, 22:44 - +91 93051 14227: 1st group nhi mid ya last me rkho
31/08/25, 22:46 - Shaurya gcet: Yes pls🙏🏻
31/08/25, 23:12 - +91 95570 26316: This message was deleted
31/08/25, 23:12 - +91 95570 26316: This message was deleted
31/08/25, 23:16 - +91 95570 26316: Group 9
Rudra Tyagi
Utkarsh Singh
Vaibhav Saini
Yash Upadhyay
Yuvraj
Ranjeet
31/08/25, 23:20 - +91 95570 26316: Group 10
Shlok
Shivanu
Somyansh
Tarun
Sarthak Sharma
Vijay
31/08/25, 23:24 - +91 96951 46906: <Media omitted>
31/08/25, 23:31 - +91 95570 26316: Group 7
Raghavender
Rashi Srivastava
Richa maurya
Shivam Jaiswal
Suraj
Vasu garg <This message was edited>
01/09/25, 00:44 - +91 93103 03911: Group 8
Riya Singh
Samiksha singh
Sanskar kashyap
Shashwat Singh
Sarthak Kumar
Siddheshwar Yadav
01/09/25, 00:44 - +91 93103 03911: Group 11
Shivansh
Sharmishtha
Siddhant
Safoora
Sakshi Kumari
Shashank Sharma
01/09/25, 00:44 - +91 93103 03911: Group 12
Sarah
Surbhi
Shraddha
Tanvy
Vallabhi
Sonali
01/09/25, 09:54 - ~ .. added ~ Rishank
01/09/25, 10:18 - ~ ꪜꪖ꠸᥇ꫝꪖꪜ ᦔꪊ᥇ꫀꪗ added ~ Sanskar Kashyap
01/09/25, 10:20 - ~ ꪜꪖ꠸᥇ꫝꪖꪜ ᦔꪊ᥇ꫀꪗ added ~ Tarush Tiwari
02/09/25, 11:36 - ~ Sumit Kumar added ~ siddheshwar yadav
03/09/25, 09:51 - +91 91936 08393 joined using a group link.
03/09/25, 21:31 - +91 93899 02284: Kal half-day h kya ??? <This message was edited>
03/09/25, 21:37 - +91 93410 82338: Kyu bhai
03/09/25, 21:38 - +91 93899 02284: Section B walebol rhe h ki unko btaya h ki klhalf-day h <This message was edited>
03/09/25, 21:38 - +91 75498 10691: Hmm
03/09/25, 21:39 - +91 93899 02284: Kitne periods k according books laani h 😁😁😁
03/09/25, 21:39 - +91 95349 01790: CR ji ko message karo. 🤣
03/09/25, 21:39 - +91 95349 01790: Personally wahi prakash dalenge
03/09/25, 21:39 - +91 93899 02284: Krta hu 😅
03/09/25, 21:40 - +91 93410 82338: <Media omitted>
03/09/25, 21:42 - +91 89530 59723: Kon bola bhai??
03/09/25, 21:43 - +91 93410 82338: <Media omitted>
03/09/25, 21:43 - +91 93899 02284: @⁨~..⁩
03/09/25, 21:46 - +91 95570 26316: Abhi tak koi informatn nh h
03/09/25, 21:46 - +91 93410 82338: <Media omitted>
03/09/25, 21:47 - +91 93899 02284: <Media omitted>
03/09/25, 21:47 - +91 93899 02284: Bhai kitne period ka bag laana h ???
03/09/25, 21:49 - +91 93410 82338: Vo to CR bhai batayenge 🙂
03/09/25, 21:50 - +91 93899 02284: <Media omitted>
03/09/25, 21:50 - +91 93410 82338: <Media omitted>
03/09/25, 21:50 - +91 89530 59723: Cr bhai kahi aur busy hai
03/09/25, 21:50 - +91 93899 02284: Aaj to Doremon ka bday h !!!
03/09/25, 21:50 - +91 93410 82338: <Media omitted>
03/09/25, 21:51 - +91 93410 82338: <Media omitted>
03/09/25, 21:56 - +91 95405 12951: Tommorow classes after lunch are postponed due to teacher's day function.
03/09/25, 21:57 - +91 93410 82338: 4 sept ko kon sa teachers day ye log mana rhe hai bhai 🤔😂
03/09/25, 21:57 - +91 95405 12951: Teacher's day function h kl...and pdso holiday h
03/09/25, 21:58 - +91 93410 82338: Okay
04/09/25, 09:36 - +91 72360 60220: <Media omitted>
04/09/25, 09:37 - +91 72360 60220: <Media omitted>
04/09/25, 10:05 - +91 72360 60220: <Media omitted>
04/09/25, 10:06 - +91 74083 04606: <Media omitted>
04/09/25, 19:34 - +91 93899 02284: Any girl wants to join our  grp (SIH) Kindly contact us ... <This message was edited>
04/09/25, 19:36 - +91 93899 02284: Girl compulsory h har grp m mam ne bola h
04/09/25, 19:43 - +91 96951 46906: <Media omitted>
04/09/25, 23:09 - +91 93899 02284: This message was deleted
04/09/25, 23:09 - +91 93051 14227: Only 52 min left 🙂
04/09/25, 23:10 - +91 93899 02284: Jldi plz btao
04/09/25, 23:10 - Surbhi gcet: Still hope alive🥹💀
04/09/25, 23:10 - +91 93051 14227: 😂😂😂
04/09/25, 23:10 - +91 93051 14227: Your grp members?
04/09/25, 23:11 - +91 93899 02284: Sunny ,rishank ,arpan , Naitik, rohit <This message was edited>
04/09/25, 23:12 - +91 93051 14227: 🙂
04/09/25, 23:12 - +91 93410 82338: <Media omitted>
04/09/25, 23:12 - +91 72360 60220: Tumko lagta hai 5 ladko ke sath ladki ayegi..

Atleast 2 ladki ho tab theek lagta hai
04/09/25, 23:12 - +91 93410 82338: <Media omitted>
04/09/25, 23:12 - +91 93899 02284: Nhi ek already h  dossri chahiye hme?? <This message was edited>
04/09/25, 23:12 - +91 72360 60220: <Media omitted>
04/09/25, 23:13 - +91 93410 82338: <Media omitted>
04/09/25, 23:13 - +91 93051 14227: Only 47 min left
04/09/25, 23:13 - +91 93899 02284: Cold coffee order open for girls  for leaving grps and joining our grp
04/09/25, 23:14 - Surbhi gcet: Are uh also searching for any team within 47 min*😂😂
04/09/25, 23:14 - +91 93410 82338: <Media omitted>
04/09/25, 23:14 - +91 93051 14227: Laadli humko team naa chahiye 😗
04/09/25, 23:15 - Surbhi gcet: Ky mtlb participate hi na krna💀😂
04/09/25, 23:15 - +91 93051 14227: Form submitted 😗
04/09/25, 23:15 - +91 93051 14227: Bhai bs 45 min
04/09/25, 23:15 - +91 93051 14227: Or
04/09/25, 23:16 - +91 93899 02284: Done ✅ grp completed
04/09/25, 23:16 - +91 93410 82338: <Media omitted>
04/09/25, 23:16 - +91 93051 14227: <Media omitted>
04/09/25, 23:20 - +91 93410 82338: Rishank bhai
04/09/25, 23:20 - +91 93410 82338: Sunoo
04/09/25, 23:20 - +91 93899 02284: Hm bolo
04/09/25, 23:21 - +91 93410 82338: <Media omitted>
04/09/25, 23:22 - +91 93899 02284: Aati h fr chli jaati h
04/09/25, 23:22 - +91 93410 82338: <Media omitted>
04/09/25, 23:22 - +91 93899 02284: This message was deleted
04/09/25, 23:23 - +91 93410 82338: This message was deleted
04/09/25, 23:23 - +91 93899 02284: 😂
06/09/25, 06:40 - +91 93051 14227: https://www.instagram.com/reel/DOMFqvbDU_X/?igsh=MXNobThyNXc1ZHljbw==
06/09/25, 20:57 - +91 95570 26316: Hey Sumit!
Anmol here.

Please ask the students to

1. Revise their basics and syntax in either C++ or Java this weekend.

2. Correctly configure C++ or Java in their local IDE. Ensure that the compiler and runtime environment are properly installed and functional on their laptops.
06/09/25, 21:51 - ~ Rishank added ~ 🙂‍↕️
08/09/25, 10:20 - ~ rohit added ~ saurav kumar
08/09/25, 12:34 - +91 63062 40198: <Media omitted>
08/09/25, 13:06 - +91 93899 02284: coa ki file ka work send krdo koi
08/09/25, 13:06 - +91 93899 02284: Plz
08/09/25, 13:07 - Rudra Tyagi gcet:
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:07 - Rudra Tyagi gcet: <Media omitted>
08/09/25, 13:08 - Rudra Tyagi gcet: 2nd Experiment
08/09/25, 13:10 - +91 93899 02284: Thanks 👍 bhai
08/09/25, 14:44 - +91 95405 12951: <Media omitted>
08/09/25, 14:44 - +91 95405 12951: <Media omitted>
08/09/25, 14:44 - +91 95405 12951: <Media omitted>
08/09/25, 20:03 - +91 95405 12951: <Media omitted>
09/09/25, 09:41 - Rudra Tyagi gcet: <Media omitted>
09/09/25, 09:41 - Rudra Tyagi gcet: <Media omitted>
09/09/25, 10:00 - ~ RISHABH MISHRA added ~ Praveen Yadav
09/09/25, 10:32 - ~ RISHABH MISHRA added ~ Zaid Ahmad
09/09/25, 13:39 - Rudra Tyagi gcet added ~ Nitesh Rajput⚔️👑
09/09/25, 18:33 - +91 93051 14227: https://www.instagram.com/reel/DOSwWvZkSgS/?igsh=MTlscHl3d2R3b3B1Mg==
10/09/25, 10:34 - Yuvraj gcet added ~ Raghav Rajput
10/09/25, 11:02 - Yuvraj gcet added ~ Ankesh
10/09/25, 12:26 - +91 63860 13880: <Media omitted>
10/09/25, 16:43 - Rohan Gcet: <Media omitted>
11/09/25, 11:46 - +91 93410 82338: Suno sab
11/09/25, 11:46 - +91 93410 82338: *Mam boli hai ki MINI PROJECT ka submit hai to DE ke Class ke baad karne ko*
11/09/25, 15:52 - ~ Ridhima added ~ ❤️
11/09/25, 19:13 - +91 95570 26316: <Media omitted>
11/09/25, 19:15 - +91 95570 26316: Iss pdf mai jiska name hai woh apna mobile no.  or parent ka  mobile no. fill kar do
11/09/25, 19:25 - +91 95570 26316: Isme save nhi ho pa rha hai mobile no .
11/09/25, 19:26 - +91 95570 26316: Sb apna mobile no. or parent ka mobile no. Mere personal no pe send kar do
11/09/25, 19:26 - +91 96951 46906: Group pe lelo
11/09/25, 19:27 - +91 95570 26316: Hnn grp pe bhej do
11/09/25, 19:27 - +91 93103 03911: Excel pr khulega
11/09/25, 19:27 - Rudra Tyagi gcet: Laptop m try karo ek baar edit karne ka
11/09/25, 19:28 - +91 94501 82582: Yeh attendance kbtk ka h??
11/09/25, 19:29 - +91 95570 26316: 29 august tak ka hai
11/09/25, 19:29 - +91 94501 82582: Oh tb thic h
11/09/25, 20:45 - +91 95570 26316: 🚨 URGENT & MANDATORY NOTICE 🚨

For: All 2nd & 3rd Year Students 🧑‍💻

Hello everyone,

Immediate registration for TCS Codevita is now compulsory for all. Please complete the following steps today!

1️⃣ Step 1: Register
Click the link below to create your account: 👉 https://codevita.tcsapps.com/

2️⃣ Step 2: Confirm & Upload
Fill out the confirmation !form and upload a screenshot 📸 of your registered homepage: 👉 https://forms.gle/tL6gUDgciNZRbfJF6

⚠ IMPORTANT ⚠
This is mandatory. Not registering will cause serious problems for your training and placements.

📋 For Class Representatives (CRs): Please ensure everyone in your class registers and fills the form. Send me a confirmation once your class is 100% registered.
11/09/25, 21:28 - +91 93103 03911: Mentioned students please fill the details urgently
11/09/25, 21:28 - +91 93103 03911: .
12/09/25, 07:38 - +91 74094 89011: This message was deleted
12/09/25, 09:29 - ~ RISHABH MISHRA added ~ Shivank Yadav
12/09/25, 09:41 - ~ ❤️ added ~ ....
12/09/25, 12:20 - +91 95570 26316: Bhejo jldi
12/09/25, 12:26 - +91 93103 03911: Rahul Verma
Ranjeet Kumar Sharma
Rashi Srivastava
Rishabh Mishra
Rishank Deshwal
Rishu Ranjan
Ritik Raj
Riya Maurya
12/09/25, 12:26 - +91 93103 03911: Send your and your parent's mobile number asap
12/09/25, 13:23 - +91 63860 13880: Jo bacche DS ki class mein nahi hai aur DSTL ki class mein the Ritu mam unka aaj ke test mein zero lgayengi aisa unhone kaha hai
12/09/25, 13:50 - +91 76518 90064: jo hai unke bhi zero hi lgnge
12/09/25, 14:47 - +91 96951 46906: Bhai maine to DSTL mei proxy lagai thi ☠️
12/09/25, 14:47 - Tarun gcet: <Media omitted>
12/09/25, 16:05 - Sarah Fatima gcet added Shraddha calling gcet
12/09/25, 18:13 - +91 93899 02284: Can anyone send class notes of dstl from topic  posets lattice
13/09/25, 14:14 - +91 93103 03911: <Media omitted>
13/09/25, 14:16 - +91 93103 03911: Inme se jisne abtak apna aur parents ka number nahi bheja hai... Kindly send them to @⁨~Sumit⁩ today itself <This message was edited>
13/09/25, 23:12 - +91 89579 53878 joined using a group link.
14/09/25, 10:50 - +91 73230 62214 joined using a group link.
14/09/25, 11:06 - +91 93103 03911: Rahul vema
14/09/25, 11:06 - +91 93103 03911: sakshi kumari
14/09/25, 11:06 - +91 93103 03911: sanchali yadav
14/09/25, 11:06 - +91 93103 03911: satvik srivastav
14/09/25, 11:06 - +91 93103 03911: Saurav kumar
14/09/25, 11:06 - +91 93103 03911: Shreya mourya
14/09/25, 11:06 - +91 93103 03911: shraddha kumari
14/09/25, 11:06 - +91 93103 03911: shivam Jaiswal
14/09/25, 11:06 - +91 93103 03911: shaurya shinha
14/09/25, 11:06 - +91 93103 03911: shashwat singh
14/09/25, 11:06 - +91 93103 03911: Yadav shivank
14/09/25, 11:06 - +91 93103 03911: These students have still not given the phone numbers
14/09/25, 11:07 - +91 93103 03911: Send me personally
14/09/25, 11:13 - ~ Ridhima pinned a message
14/09/25, 16:59 - +91 95570 26316: For the students who asked for a tutorial during last class through which they can learn C++

https://youtu.be/-TkoO8Z07hI
14/09/25, 18:28 - +91 75498 10691: Bhayy
14/09/25, 18:28 - +91 75498 10691: Kisi ne
14/09/25, 18:28 - +91 75498 10691: Dstl ki
14/09/25, 18:28 - +91 75498 10691: Assignment kri h <This message was edited>
14/09/25, 18:28 - +91 75498 10691: Toh vej do
14/09/25, 18:28 - +91 75498 10691: Please

In [57]:
# pattern = '^\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?(?:am|pm|AM|PM)\s*-\s*(.+?):\s*(.*)$'
# pattern = '^\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?(?:am|pm|AM|PM)\s-\s(.+?):\s(.*)'
# pattern = '^(\d{1,2}/\d{1,2}/\d{2,4}),\s(\d{1,2}:\d{2})\s?(am|pm|AM|PM)\s*-\s*(.+?):\s*(.*)'
# pattern = '^^(\d{1,2}/\d{1,2}/\d{2,4}),\s\d{1,2}:\d{2}.*?-\s(.*)'
# pattern = '^\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}.*?\b(?:am|pm|AM|PM)\s*-\s*([^:]+:\s.*)$'
# dates pattern = ^(\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?(?:am|pm|AM|PM))
patternMsg = '\d{1,2}/\d{1,2}/\d{2,4},.*?-\s*'
patternDate = '(\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2})[\u202F\s]?(am|pm|AM|PM)'

In [58]:
messages = re.split(patternMsg, data,)[1:]
messages
print(len(messages))

1606

In [ ]:
dates = re.findall(patternDate, data)
dates
print(len(dates))

[]

In [60]:
df = pd.DataFrame({
    "dates": dates,
    "message": messages
})

ValueError: All arrays must be of the same length

In [ ]:
df

                    dates                                            message
0    (14/02/24, 2:35, pm)  Messages and calls are end-to-end encrypted. O...
1    (13/03/24, 5:56, pm)                                  Shauryaaa: Arey\n
2    (13/03/24, 5:56, pm)           Shauryaaa: Kaun se duniya me rahti hai\n
3    (13/03/24, 6:12, pm)                                Tanvy Verma: Kyaa\n
4    (13/03/24, 6:12, pm)                             Tanvy Verma: Bolo...\n
..                    ...                                                ...
662  (14/01/26, 8:25, pm)                     Tanvy Verma: <Media omitted>\n
663  (14/01/26, 8:25, pm)                     Tanvy Verma: <Media omitted>\n
664  (14/01/26, 8:26, pm)                     Tanvy Verma: <Media omitted>\n
665  (14/01/26, 8:27, pm)                     Tanvy Verma: <Media omitted>\n
666  (14/01/26, 8:29, pm)                     Tanvy Verma: <Media omitted>\n

[667 rows x 2 columns]

In [ ]:
df["dates"] = df["dates"].astype(str)

In [ ]:
df['dates'] = df['dates'].str.strip()
df['dates'] = df['dates'].str.replace(r'[()]', '', regex=True)

In [ ]:
df

                      dates                                            message
0    '14/02/24, 2:35', 'pm'  Messages and calls are end-to-end encrypted. O...
1    '13/03/24, 5:56', 'pm'                                  Shauryaaa: Arey\n
2    '13/03/24, 5:56', 'pm'           Shauryaaa: Kaun se duniya me rahti hai\n
3    '13/03/24, 6:12', 'pm'                                Tanvy Verma: Kyaa\n
4    '13/03/24, 6:12', 'pm'                             Tanvy Verma: Bolo...\n
..                      ...                                                ...
662  '14/01/26, 8:25', 'pm'                     Tanvy Verma: <Media omitted>\n
663  '14/01/26, 8:25', 'pm'                     Tanvy Verma: <Media omitted>\n
664  '14/01/26, 8:26', 'pm'                     Tanvy Verma: <Media omitted>\n
665  '14/01/26, 8:27', 'pm'                     Tanvy Verma: <Media omitted>\n
666  '14/01/26, 8:29', 'pm'                     Tanvy Verma: <Media omitted>\n

[667 rows x 2 columns]

In [ ]:
df['dates'] = df['dates'].str.replace(', pm', ' PM', regex=False)
df['dates'] = df['dates'].str.replace(', am', ' AM', regex=False)

In [ ]:
df['date'] = df['dates'].str.extract(r"(\d{2}/\d{2}/\d{2}), (\d{1,2}:\d{2}).*?(am|pm)")[0] + ' ' + df['dates'].str.extract(r"(\d{2}/\d{2}/\d{2}), (\d{1,2}:\d{2}).*?(am|pm)")[1] + ' ' + df['dates'].str.extract(r"(\d{2}/\d{2}/\d{2}), (\d{1,2}:\d{2}).*?(am|pm)")[2]
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%y %I:%M %p')

In [ ]:
df

,dates,message,date
0,"'14/02/24, 2:35', 'pm'",Messages and calls are end-to-end encrypted. O...,2024-02-14 14:35:00
1,"'13/03/24, 5:56', 'pm'",Shauryaaa: Arey\n,2024-03-13 17:56:00
2,"'13/03/24, 5:56', 'pm'",Shauryaaa: Kaun se duniya me rahti hai\n,2024-03-13 17:56:00
3,"'13/03/24, 6:12', 'pm'",Tanvy Verma: Kyaa\n,2024-03-13 18:12:00
4,"'13/03/24, 6:12', 'pm'",Tanvy Verma: Bolo...\n,2024-03-13 18:12:00
...,...,...,...
662,"'14/01/26, 8:25', 'pm'",Tanvy Verma: <Media omitted>\n,2026-01-14 20:25:00
663,"'14/01/26, 8:25', 'pm'",Tanvy Verma: <Media omitted>\n,2026-01-14 20:25:00
664,"'14/01/26, 8:26', 'pm'",Tanvy Verma: <Media omitted>\n,2026-01-14 20:26:00
665,"'14/01/26, 8:27', 'pm'",Tanvy Verma: <Media omitted>\n,2026-01-14 20:27:00
666,"'14/01/26, 8:29', 'pm'",Tanvy Verma: <Media omitted>\n,2026-01-14 20:29:00

In [ ]:
users = []
texts = []

for msg in messages:
    if ':' in msg:
        user, text = msg.split(':', 1)
        users.append(user.strip())
        texts.append(text.strip())
    else:
        users.append("group_notification")
        texts.append(msg.strip())

In [ ]:
df['user'] = users

In [ ]:
df['message'] = texts

In [ ]:
df

,dates,message,date,user
0,"'14/02/24, 2:35', 'pm'",Messages and calls are end-to-end encrypted. O...,2024-02-14 14:35:00,group_notification
1,"'13/03/24, 5:56', 'pm'",Arey,2024-03-13 17:56:00,Shauryaaa
2,"'13/03/24, 5:56', 'pm'",Kaun se duniya me rahti hai,2024-03-13 17:56:00,Shauryaaa
3,"'13/03/24, 6:12', 'pm'",Kyaa,2024-03-13 18:12:00,Tanvy Verma
4,"'13/03/24, 6:12', 'pm'",Bolo...,2024-03-13 18:12:00,Tanvy Verma
...,...,...,...,...
662,"'14/01/26, 8:25', 'pm'",<Media omitted>,2026-01-14 20:25:00,Tanvy Verma
663,"'14/01/26, 8:25', 'pm'",<Media omitted>,2026-01-14 20:25:00,Tanvy Verma
664,"'14/01/26, 8:26', 'pm'",<Media omitted>,2026-01-14 20:26:00,Tanvy Verma
665,"'14/01/26, 8:27', 'pm'",<Media omitted>,2026-01-14 20:27:00,Tanvy Verma
666,"'14/01/26, 8:29', 'pm'",<Media omitted>,2026-01-14 20:29:00,Tanvy Verma

In [ ]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute

df['only_date'] = df['date'].dt.date
df['month_num'] = df['date'].dt.month
df['day_name'] = df['date'].dt.day_name()

In [ ]:
df.drop(columns=['dates'], inplace=True)

In [ ]:
df

,message,date,user,year,month,day,hour,minute,only_date,month_num,day_name
0,Messages and calls are end-to-end encrypted. O...,2024-02-14 14:35:00,group_notification,2024,February,14,14,35,2024-02-14,2,Wednesday
1,Arey,2024-03-13 17:56:00,Shauryaaa,2024,March,13,17,56,2024-03-13,3,Wednesday
2,Kaun se duniya me rahti hai,2024-03-13 17:56:00,Shauryaaa,2024,March,13,17,56,2024-03-13,3,Wednesday
3,Kyaa,2024-03-13 18:12:00,Tanvy Verma,2024,March,13,18,12,2024-03-13,3,Wednesday
4,Bolo...,2024-03-13 18:12:00,Tanvy Verma,2024,March,13,18,12,2024-03-13,3,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...
662,<Media omitted>,2026-01-14 20:25:00,Tanvy Verma,2026,January,14,20,25,2026-01-14,1,Wednesday
663,<Media omitted>,2026-01-14 20:25:00,Tanvy Verma,2026,January,14,20,25,2026-01-14,1,Wednesday
664,<Media omitted>,2026-01-14 20:26:00,Tanvy Verma,2026,January,14,20,26,2026-01-14,1,Wednesday
665,<Media omitted>,2026-01-14 20:27:00,Tanvy Verma,2026,January,14,20,27,2026-01-14,1,Wednesday
666,<Media omitted>,2026-01-14 20:29:00,Tanvy Verma,2026,January,14,20,29,2026-01-14,1,Wednesday

In [ ]:
period = []
for hour in df[['day', 'hour']]['hour']:
    if hour == 23:
        period.append(str(hour) + '-' + str(00))
    elif hour == 0:
        period.append(str('00') + '-' + str(hour + 1))
    else: 
        period.append(str(hour) + '-' + str(hour + 1))

In [ ]:
df['period'] = period

In [ ]:
df

,message,date,user,year,month,day,hour,minute,only_date,month_num,day_name,period
0,Messages and calls are end-to-end encrypted. O...,2024-02-14 14:35:00,group_notification,2024,February,14,14,35,2024-02-14,2,Wednesday,14-15
1,Arey,2024-03-13 17:56:00,Shauryaaa,2024,March,13,17,56,2024-03-13,3,Wednesday,17-18
2,Kaun se duniya me rahti hai,2024-03-13 17:56:00,Shauryaaa,2024,March,13,17,56,2024-03-13,3,Wednesday,17-18
3,Kyaa,2024-03-13 18:12:00,Tanvy Verma,2024,March,13,18,12,2024-03-13,3,Wednesday,18-19
4,Bolo...,2024-03-13 18:12:00,Tanvy Verma,2024,March,13,18,12,2024-03-13,3,Wednesday,18-19
...,...,...,...,...,...,...,...,...,...,...,...,...
662,<Media omitted>,2026-01-14 20:25:00,Tanvy Verma,2026,January,14,20,25,2026-01-14,1,Wednesday,20-21
663,<Media omitted>,2026-01-14 20:25:00,Tanvy Verma,2026,January,14,20,25,2026-01-14,1,Wednesday,20-21
664,<Media omitted>,2026-01-14 20:26:00,Tanvy Verma,2026,January,14,20,26,2026-01-14,1,Wednesday,20-21
665,<Media omitted>,2026-01-14 20:27:00,Tanvy Verma,2026,January,14,20,27,2026-01-14,1,Wednesday,20-21
666,<Media omitted>,2026-01-14 20:29:00,Tanvy Verma,2026,January,14,20,29,2026-01-14,1,Wednesday,20-21